code --install-extension amazonwebservices.aws-toolkit-vscode
code --install-extension codezombiech.gitignore
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension hbenl.vscode-test-explorer
code --install-extension mhutchie.git-graph
code --install-extension ms-azuretools.vscode-azurefunctions
code --install-extension ms-azuretools.vscode-azureresourcegroups
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-dotnettools.csharp
code --install-extension ms-kubernetes-tools.vscode-kubernetes-tools
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vscode.azure-account
code --install-extension ms-vscode.hexeditor
code --install-extension ms-vscode.test-adapter-converter
code --install-extension redhat.vscode-yaml
code --install-extension aws-scripting-guy.cform
code --install-extension kddejong.vscode-cfn-lint
code --install-extension Arjun.swagger-viewer
code --install-extension rangav.vscode-thunder-client
code --install-extension ms-vscode.powershell
code --install-extension eamodio.gitlens
code --install-extension editorconfig.editorconfig
code --install-extension Orta.vscode-jest